baseurl: "/"
url: https://tarbase.com
name: tarbase
company_name: tarbase
full_company_name: tarbase, lda.
description: Building, automating galaxies, stars and clouds

paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/Lisbon'

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-sass-converter
